"""Build derived outputs from raw batches.

raw/ --(decode, dedupe, validate)--> clean/questions.json
                                  -> export/portapak-questions.json (+ .d.ts)
                                  -> reports/validation-report.json and .md

Derived files are regenerated in full on every build and written atomically.
Raw files are only ever read here.
"""

from __future__ import annotations

import logging
from collections import Counter, OrderedDict
from typing import Any, Dict, List, Optional, Tuple

from . import __version__
from .clean import CleanRecord, clean_record, comparison_key
from .store import DataStore, atomic_write_json, atomic_write_text, utc_now
from .validate import ISSUE_CODES, Issue, is_valid, validate_record

log = logging.getLogger(__name__)

EXPORT_FORMAT = "portapak-quiz-questions"
EXPORT_SCHEMA_VERSION = 1

ATTRIBUTION = {
    "source": "Open Trivia Database",
    "url": "https://opentdb.com/",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "notice": ("Questions from the Open Trivia Database (opentdb.com), licensed under CC BY-SA 4.0. "
               "Text was decoded and whitespace-normalised; records failing validation were excluded."),
}

TS_TYPES = """\
// Generated by otdb-downloader (PortaPak Edition). Types for portapak-questions.json.
// Question content: Open Trivia Database, CC BY-SA 4.0 (https://opentdb.com/).

export type QuestionType = "multiple" | "boolean";
export type Difficulty = "easy" | "medium" | "hard";

export interface PortaPakQuestion {
  /** Stable content-derived identifier, e.g. "otdb-3f2a9c1b0d4e5f67". */
  id: string;
  categoryId: number;
  category: string;
  type: QuestionType;
  difficulty: Difficulty;
  question: string;
  correctAnswer: string;
  /** 3 entries for "multiple", 1 for "boolean". Not shuffled. */
  incorrectAnswers: string[];
}

export interface PortaPakCategory {
  id: number;
  name: string;
  questionCount: number;
}

export interface PortaPakAttribution {
  source: string;
  url: string;
  licence: string;
  licenceUrl: string;
  notice: string;
}

export interface PortaPakQuestionFile {
  format: "portapak-quiz-questions";
  schemaVersion: 1;
  generatedAt: string;
  generator: string;
  attribution: PortaPakAttribution;
  categories: PortaPakCategory[];
  questions: PortaPakQuestion[];
}
"""


def _category_names(store: DataStore) -> Tuple[Dict[int, str], Optional[str]]:
    snap = store.latest_categories_snapshot()
    if snap is None:
        return {}, None
    rel, doc = snap
    cats = (doc.get("response") or {}).get("trivia_categories") or []
    return {int(c["id"]): c["name"] for c in cats if isinstance(c, dict) and "id" in c}, rel


def load_records(store: DataStore) -> Tuple[List[CleanRecord], int, int]:
    """Return (unique records in raw order, total raw records, batch count)."""
    unique: "OrderedDict[str, CleanRecord]" = OrderedDict()
    total = 0
    batches = 0
    for rel, doc in store.iter_raw_batches():
        batches += 1
        params = (doc.get("request") or {}).get("params") or {}
        encoding = params.get("encode", "url3986")
        results = (doc.get("response") or {}).get("results") or []
        for i, raw in enumerate(results):
            total += 1
            rec = clean_record(raw, category_id=doc.get("category_id"), encoding=encoding,
                               raw_batch=rel, raw_index=i, fetched_at=doc.get("fetched_at"))
            if rec.fingerprint not in unique:
                unique[rec.fingerprint] = rec
    return list(unique.values()), total, batches


def build(store: DataStore) -> Dict[str, Any]:
    store.require_initialised()
    category_names, cat_snapshot = _category_names(store)
    records, raw_total, batch_count = load_records(store)
    state = store.load_state()

    results: List[Tuple[CleanRecord, List[Issue]]] = []
    seen_questions: Dict[str, CleanRecord] = {}
    for rec in records:
        issues = validate_record(rec, category_names)
        if rec.question:
            key = comparison_key(rec.question)
            first = seen_questions.get(key)
            if first is not None:
                same_answer = (first.correct_answer or "").strip().casefold() == (rec.correct_answer or "").strip().casefold()
                issues.append(Issue("duplicate_question",
                                    f"same text as {first.id} ({'same' if same_answer else 'different'} correct answer)"))
            elif is_valid(issues):
                # only a valid record can "claim" a question text
                seen_questions[key] = rec
        results.append((rec, issues))

    generated_at = utc_now()
    clean_doc = {
        "format": "otdb-clean-questions",
        "schemaVersion": 1,
        "generatedAt": generated_at,
        "generator": f"otdb-downloader {__version__}",
        "attribution": ATTRIBUTION,
        "records": [_clean_entry(rec, issues, category_names) for rec, issues in results],
    }
    atomic_write_json(store.root / "clean" / "questions.json", clean_doc)

    valid = [(rec, issues) for rec, issues in results if is_valid(issues)]
    per_cat = Counter(rec.category_id for rec, _ in valid)
    export_doc = {
        "format": EXPORT_FORMAT,
        "schemaVersion": EXPORT_SCHEMA_VERSION,
        "generatedAt": generated_at,
        "generator": f"otdb-downloader {__version__}",
        "attribution": ATTRIBUTION,
        "categories": [
            {"id": cid, "name": category_names[cid], "questionCount": per_cat.get(cid, 0)}
            for cid in sorted(category_names) if per_cat.get(cid, 0) > 0
        ],
        "questions": [
            {
                "id": rec.id,
                "categoryId": rec.category_id,
                "category": rec.category,
                "type": rec.type,
                "difficulty": rec.difficulty,
                "question": rec.question,
                "correctAnswer": rec.correct_answer,
                "incorrectAnswers": list(rec.incorrect_answers or []),
            }
            for rec, _ in valid
        ],
    }
    atomic_write_json(store.root / "export" / "portapak-questions.json", export_doc)
    atomic_write_text(store.root / "export" / "portapak-questions.d.ts", TS_TYPES)

    report = make_report(results, raw_total, batch_count, category_names, state, generated_at, cat_snapshot)
    atomic_write_json(store.root / "reports" / "validation-report.json", report)
    atomic_write_text(store.root / "reports" / "validation-report.md", render_markdown(report))
    log.info("Build complete: %d unique records, %d valid, %d rejected",
             report["totals"]["unique_records"], report["totals"]["valid"], report["totals"]["rejected"])
    return report


def _clean_entry(rec: CleanRecord, issues: List[Issue], names: Dict[int, str]) -> Dict[str, Any]:
    return {
        "id": rec.id,
        "category": {"id": rec.category_id, "name": rec.category,
                     "downloadedAs": names.get(rec.category_id) if rec.category_id is not None else None},
        "type": rec.type,
        "difficulty": rec.difficulty,
        "question": rec.question,
        "correct_answer": rec.correct_answer,
        "incorrect_answers": rec.incorrect_answers,
        "valid": is_valid(issues),
        "issues": [i.to_dict() for i in issues],
        "source": {"raw_batch": rec.raw_batch, "raw_index": rec.raw_index, "fetched_at": rec.fetched_at},
    }


def make_report(results: List[Tuple[CleanRecord, List[Issue]]], raw_total: int, batch_count: int,
                names: Dict[int, str], state: Dict[str, Any], generated_at: str,
                cat_snapshot: Optional[str]) -> Dict[str, Any]:
    rejection_reasons: Counter = Counter()
    warning_reasons: Counter = Counter()
    by_cat: Dict[Any, Dict[str, Any]] = {}
    by_diff: Dict[str, Counter] = {}
    by_type: Dict[str, Counter] = {}
    rejected: List[Dict[str, Any]] = []

    for rec, issues in results:
        ok = is_valid(issues)
        errors = sorted({i.code for i in issues if i.severity == "error"})
        warnings = sorted({i.code for i in issues if i.severity == "warning"})
        rejection_reasons.update(errors)
        warning_reasons.update(warnings)
        key = rec.category_id
        c = by_cat.setdefault(key, {"downloaded": 0, "valid": 0, "rejected": 0,
                                    "multiple": 0, "boolean": 0, "easy": 0, "medium": 0, "hard": 0})
        c["downloaded"] += 1
        c["valid" if ok else "rejected"] += 1
        if ok:
            if rec.type in ("multiple", "boolean"):
                c[rec.type] += 1
            if rec.difficulty in ("easy", "medium", "hard"):
                c[rec.difficulty] += 1
        d = by_diff.setdefault(str(rec.difficulty), Counter())
        d["downloaded"] += 1
        d["valid" if ok else "rejected"] += 1
        t = by_type.setdefault(str(rec.type), Counter())
        t["downloaded"] += 1
        t["valid" if ok else "rejected"] += 1
        if not ok:
            rejected.append({
                "id": rec.id, "category_id": rec.category_id, "question": rec.question,
                "correct_answer": rec.correct_answer,
                "issues": [i.to_dict() for i in issues if i.severity == "error"],
                "raw_batch": rec.raw_batch, "raw_index": rec.raw_index,
            })

    cat_state = state.get("categories", {})
    categories = []
    ids = sorted(set(names) | {k for k in by_cat if isinstance(k, int)})
    for cid in ids:
        c = by_cat.get(cid, {"downloaded": 0, "valid": 0, "rejected": 0, "multiple": 0, "boolean": 0,
                             "easy": 0, "medium": 0, "hard": 0})
        cs = cat_state.get(str(cid), {})
        categories.append({
            "id": cid, "name": names.get(cid, f"(unknown id {cid})"),
            "api_reported_total": cs.get("reported_total"),
            "download_status": cs.get("status", "not started"),
            "finish_reason": cs.get("finish_reason"),
            **c,
        })

    totals = {
        "raw_batches": batch_count,
        "raw_records": raw_total,
        "duplicate_records_removed": raw_total - len(results),
        "unique_records": len(results),
        "valid": sum(1 for _, i in results if is_valid(i)),
        "rejected": sum(1 for _, i in results if not is_valid(i)),
        "records_with_warnings": sum(1 for _, i in results if any(x.severity == "warning" for x in i)),
    }
    return {
        "generatedAt": generated_at,
        "generator": f"otdb-downloader {__version__}",
        "categories_snapshot": cat_snapshot,
        "totals": totals,
        "rejection_reasons": dict(rejection_reasons.most_common()),
        "warning_reasons": dict(warning_reasons.most_common()),
        "issue_descriptions": {k: {"severity": v[0], "description": v[1]} for k, v in ISSUE_CODES.items()},
        "by_category": categories,
        "by_difficulty": {k: dict(v) for k, v in sorted(by_diff.items())},
        "by_type": {k: dict(v) for k, v in sorted(by_type.items())},
        "rejected_records": rejected,
        "last_runs": state.get("runs", [])[-5:],
    }


def render_markdown(r: Dict[str, Any]) -> str:
    t = r["totals"]
    out = [
        "# OpenTDB download and validation report",
        "",
        f"Generated {r['generatedAt']} by {r['generator']}.",
        "",
        "## Totals",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Raw batches | {t['raw_batches']} |",
        f"| Raw records downloaded | {t['raw_records']} |",
        f"| Exact duplicate records removed | {t['duplicate_records_removed']} |",
        f"| Unique records | {t['unique_records']} |",
        f"| **Valid (exported)** | **{t['valid']}** |",
        f"| Rejected | {t['rejected']} |",
        f"| Records with warnings (kept) | {t['records_with_warnings']} |",
        "",
        "## Rejection reasons",
        "",
    ]
    if r["rejection_reasons"]:
        out += ["| Reason | Records | Description |", "|---|---:|---|"]
        for code, n in r["rejection_reasons"].items():
            out.append(f"| `{code}` | {n} | {r['issue_descriptions'][code]['description']} |")
    else:
        out.append("No records were rejected.")
    out += ["", "## Warnings (records kept)", ""]
    if r["warning_reasons"]:
        out += ["| Warning | Records | Description |", "|---|---:|---|"]
        for code, n in r["warning_reasons"].items():
            out.append(f"| `{code}` | {n} | {r['issue_descriptions'][code]['description']} |")
    else:
        out.append("None.")
    out += [
        "", "## By category", "",
        "| ID | Category | API reported | Downloaded | Valid | Rejected | Multiple | True/False | Easy | Medium | Hard | Status |",
        "|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for c in r["by_category"]:
        rep = "" if c["api_reported_total"] is None else c["api_reported_total"]
        out.append(f"| {c['id']} | {c['name']} | {rep} | {c['downloaded']} | {c['valid']} | {c['rejected']} | "
                   f"{c['multiple']} | {c['boolean']} | {c['easy']} | {c['medium']} | {c['hard']} | "
                   f"{c['download_status']} |")
    out += ["", "## By difficulty", "", "| Difficulty | Downloaded | Valid | Rejected |", "|---|---:|---:|---:|"]
    for k, v in r["by_difficulty"].items():
        out.append(f"| {k} | {v.get('downloaded', 0)} | {v.get('valid', 0)} | {v.get('rejected', 0)} |")
    out += ["", "## By question type", "", "| Type | Downloaded | Valid | Rejected |", "|---|---:|---:|---:|"]
    labels = {"multiple": "multiple (multiple choice)", "boolean": "boolean (true/false)"}
    for k, v in r["by_type"].items():
        out.append(f"| {labels.get(k, k)} | {v.get('downloaded', 0)} | {v.get('valid', 0)} | {v.get('rejected', 0)} |")
    out += ["", "## Rejected records", ""]
    if r["rejected_records"]:
        out += ["| ID | Category | Question | Issues |", "|---|---:|---|---|"]
        for x in r["rejected_records"]:
            q = (x["question"] or "(missing)").replace("|", "\\|")
            if len(q) > 80:
                q = q[:77] + "..."
            issues = "; ".join(f"{i['code']}" + (f" ({i['detail']})" if i.get("detail") else "")
                               for i in x["issues"]).replace("|", "\\|")
            out.append(f"| `{x['id']}` | {x['category_id']} | {q} | {issues} |")
    else:
        out.append("None.")
    out.append("")
    return "\n".join(out)
