// Generated by otdb-downloader (PortaPak Edition). Types for portapak-questions.json.
// Question content: Open Trivia Database, CC BY-SA 4.0 (https://opentdb.com/).

export type QuestionType = "multiple" | "boolean";
export type Difficulty = "easy" | "medium" | "hard";

export interface PortaPakQuestion {
  /** Stable content-derived identifier, e.g. "otdb-3f2a9c1b0d4e5f67". */
  id: string;
  categoryId: number;
  category: string;
  type: QuestionType;
  difficulty: Difficulty;
  question: string;
  correctAnswer: string;
  /** 3 entries for "multiple", 1 for "boolean". Not shuffled. */
  incorrectAnswers: string[];
}

export interface PortaPakCategory {
  id: number;
  name: string;
  questionCount: number;
}

export interface PortaPakAttribution {
  source: string;
  url: string;
  licence: string;
  licenceUrl: string;
  notice: string;
}

export interface PortaPakQuestionFile {
  format: "portapak-quiz-questions";
  schemaVersion: 1;
  generatedAt: string;
  generator: string;
  attribution: PortaPakAttribution;
  categories: PortaPakCategory[];
  questions: PortaPakQuestion[];
}
